### ISSUE TITLE
babel view not working when creating a translation for a dexterity type

### ISSUE THREAD

**Issue by jihaisse** [plone/plone.app.multilingual#180]
When you want to translate a dexterity content type, the babel view is not called.
You have to save the translation, then edit with the babel view to make it work.
It's not really usable for lambda users.

**Comment by djowett** [comment]
You probably want to give more info here, like screenshots & which version you are using? 
I don't see this with 1.x branch, selecting (for example) "Create German" from the drop down menu opens up the Babel edit form with sensible settings.
![create_german](https://cloud.githubusercontent.com/assets/1470021/9990557/3ba60626-605a-11e5-94c0-3a952302b369.png)

**Comment by jihaisse** [comment]
When I translate an Archetype, it's ok, I have the babel view. Not for Dexterity.

![translate](https://cloud.githubusercontent.com/assets/498003/9991692/8c1489ae-606c-11e5-93a3-86118d222678.png)
![form](https://cloud.githubusercontent.com/assets/498003/9991696/91c51454-606c-11e5-9c4e-c987f1bf0b8d.png)

**Comment by djowett** [comment]
And which version? Can you see which template you have ? (look in the classes of the body tag)

**Comment by jihaisse** [comment]
I's plone.app.multilingual 1.2.2 on Plone 4.3.6.

This is all classes I have in the body : template-quote portaltype-folder site-en section-peace-resources subsection-be-inspired subsection-be-inspired-quotations icons-on userrole-manager userrole-authenticated userrole-owner

**Comment by djowett** [comment]
Yep, similar enough to what I'm using (1.2.2 & Plone 4.3.2)
"template-quote" is the relevant bit - a template from your custom type.
From what I see in the code... you may need to set "redirect on creation to babel view" under the language settings....
![multilingualsettings](https://cloud.githubusercontent.com/assets/1470021/9993905/49bdc826-6072-11e5-9693-846ab60f53a9.png)

Does that help?

**Comment by jihaisse** [comment]
Nope, it's already checked...

**Comment by djowett** [comment]
And the link for "Créer English" ends with "/babel_edit"?

**Comment by jihaisse** [comment]
No, this is what I have in the links : http://localhost:8080/Plone/fr/ressources-de-paix/sinspirer/citations/merci_a_la_vie/@@create_translation?language=en

**Comment by djowett** [comment]
Hmm, sorry that's getting beyond me.   I think you end up in AddViewTraverser::traverse() in add.py - but where you go from there, I'm not certain.

**Comment by bloodbare** [comment]
On pam 1.2.2 it should redirect to ++addtranslation++ view if you have the
checkbox on control panel active. Are you sure you are using 1.2.2 and when
you click to create english it shows the add form with the
@@create_translation on the url ?

When you click that url which is the url you get on the browser ?

El dl., 21 set. 2015 a les 17:12, Daniel Jowett (<notifications@github.com>)
va escriure:

**Comment by jihaisse** [comment]
Yes, I'm using pam 1.2.2 and the link in the create english is http://localhost:8080/Plone/fr/ressources-de-paix/sinspirer/citations/merci_a_la_vie/@@create_translation?language=en and I've got the checkbox on control panel active.

But when I click it, I'm redirected to : http://localhost:8080/Plone/en/peace-resources/be-inspired/quotations/++addtranslation++Quote

**Comment by GrainesDePaix** [comment]
Hi Jihaisse, hi all helpers here,
Thanks to all for checking this out for us. 

I'm the president of our NGO and a rather low-tech, but admin-knowledgeable.
We use external volunteer translators so we need a smooth, easy to use, non-tech translation module an also the Translator management module (nothing received yet)
I hope a Dexterity expert can help us solve these major issues as we're are now over 1 month late in our launch, and still can't give the user access to translators.

Current situation
I just tried again: the translation module remains UNUSABLE in DEXTERITY.
1. The instructions given by Julien, to click on translate, then create title: can't be done since the TITLE info is missing on the empty page, 
2. The translator has no indication either of who is the AUTHOR, so he can't add him either.
3. A search of the author's name through SEARCH is 0 result because no Authors are in English for the same reason.

Currently, we do NOT have this problem on our 2005 CMS. We enter a quote, add the author before saving, then save. Then we translate: all the fields are prefilled with the French text, including the author. This is what we want please. If you'd like, I can give you the admin code of our EZ Publish CMS to see how it works. It's a small piece of code development that was done for the author link.

Please help us find the right expert.
Thanks to all, Delia

**Comment by GrainesDePaix** [comment]
We chose PLONE for it's multilingual capabilities to let us display and manage 10 languages, 
We have a second most serious TRANSLATION issue.Not related to Dexterity
Just click here to understand:
http://grainesdepaix.bayardserviceweb.com/not_translated_yet/37d63ea7ba6344d7b4fba2eb906d6871?set_language=en 
You can imagine how this affects negatively our viewers and how many hundreds of pages will have this issue per language!
Other multilingual CMSs dont have this issue.
We thus are urgently waiting for untranslated pages to display the language that DOES exist, and if there are both English and French, that English have priority 1 and French have priority 2.
Standard on EZ Publish since before 2005.looking forward to the responses of the Plone specialists online here.
Sincerely, Delia

**Comment by GrainesDePaix** [comment]
We chose PLONE for it's multilingual capabilities to let us display and manage 10 languages, 
We have a second most serious TRANSLATION issue.Not related to Dexterity
Just click here to understand:
http://grainesdepaix.bayardserviceweb.com/not_translated_yet/37d63ea7ba6344d7b4fba2eb906d6871?set_language=en 
THis happens in at least 2 cases: 
- the content is not translated
- the content is translated by the universal link was not put in.
You can imagine how this affects negatively our viewers and how many hundreds of pages will have this issue per language!
Other multilingual CMSs (EZ, Drupal) dont have this issue, nor do they need to click on Universal link.
We thus are urgently waiting for untranslated pages to display the language that DOES exist, and if there are both English and French, that English have priority 1 and French have priority 2.
Standard on EZ Publish since before 2005.looking forward to the responses of the Plone specialists online here.

Also can one expect soon from PLONE a solution whereby the universal link is automated, without manual intervention?
Sincerely, Delia

**Comment by jihaisse** [comment]
Hi @bloodbare and @djowett 
So, I'm still getting stuck...

I have :
![capture d ecran 2015-10-09 a 09 41 35](https://cloud.githubusercontent.com/assets/498003/10388426/242b1766-6e6a-11e5-8698-b5b4be7952dc.png)

In my buildout I have :
plone.app.multilingual[archetypes, dexterity]
plone.multilingualbehavior
[versions]
plone.app.multilingual = 1.2.2
archetypes.multilingual = 1.2

In the control panel :
![capture d ecran 2015-10-09 a 09 44 51](https://cloud.githubusercontent.com/assets/498003/10388467/79730c92-6e6a-11e5-9835-50425a0031d4.png)

When I click on "translate" on a dexterity type, it is redirected to ++addtranslation++ view, but there is no babel view here.
If I save the translation (by setting only the title for example) and click on "edit with babel view", I've got the babel view...

**Comment by bloodbare** [comment]
Hey @jihaisse @GrainesDePaix, 

First sorry for some mess, the evolution of plone.app.multilingual, as a difficult subject is something that has changes a lot from 1.0 - 1.2 - 2.x - 3.x. I really would recomend first of all that as soon as you can you could move to plone 5 (multilingual 3.x) where its been a really hard work on cleaning and improving the multilingual support so its included on core.

@jihaisse I would add a pdb on https://github.com/plone/plone.app.multilingual/blob/1.x/src/plone/app/multilingual/browser/add.py#L33 to know why n ++addtranslation++ there is no babel_view

@GrainesDePaix I don't know if I understood correctly, the not_translated_yet page apears because you have a policy option to show it or show the closest content you want. Imagine you have a document in english and you ask to the system the dutch translation, if you don't have, what would you do ? we are returning two main options : the closest element or a not translated page. 

I recomend everybody to see the presentation with the three multilingual core concepts:

http://pt.slideshare.net/bloodbare/ploneappmultilingual?nomobile=true&smtNoRedir=1

**Comment by jihaisse** [comment]
Thanks for the tip @bloodbare 
I've set a breakpoint in add.py.

What I saw is in zope.interface.adapter.py:527 when calling (add.py:43)

```
add_view = queryMultiAdapter((self.context, self.request, ti),
                                         name='babel_view')
```

```
def queryMultiAdapter(self, objects, provided, name=u'', default=None):
        factory = self.lookup(map(providedBy, objects), provided, name)
        if factory is None:
            return default
        ...
```

factory is None.

What does this mean ? It can't find the babel_view ?

**Comment by bloodbare** [comment]
I see what happens, there is a registration on configure.zcml that defined
the babel view for
(Products.CMFCore.interfaces.IFolderish
Products.CMFDefault.interfaces.ICMFDefaultSkin
plone.dexterity.interfaces.IDexterityFTI)

so if the first context is not folderish then it will not work! Sorry about
this stupid error, you can provide a fix for it? I can't remember why I
decided to use IFolderish there, but I think there was a reason. Maybe you
can provide a specific adapter for you contenttypes on your package to
solve it now.




El dv., 9 oct. 2015 a les 15:30, jihaisse (<notifications@github.com>) va
escriure:

**Comment by jihaisse** [comment]
@bloodbare hey, that's a good news.
How could I fix it ?
By what interface should I replace the IFolderish ? IContentish ?

**Comment by agitator** [comment]
should be fixed with https://github.com/plone/plone.app.multilingual/pull/190

exchanged Products.CMFDefault.interfaces.ICMFDefaultSkin with plone.app.multilingual.interfaces.IPloneAppMultilingualInstalled as more appropriate interface

**Comment by djowett** [comment]
@agitator it looks a useful fix, but the OP (@jihaisse) is on 1.2.2, so the fix needs to go into that branch too

**Comment by jihaisse** [comment]
I tried that fix in 1.2.2, this works.
Thanks, I will try to make a commit.

**Comment by jihaisse** [comment]
https://github.com/plone/plone.app.multilingual/pull/192 should fix it for 1.x branch

**Comment by jensens** [comment]
This is an old issue addressing an old version of plone.app.multilingual and probably very outdated.
I close this issue now. If I am wrong please reopen the issue.
