### ISSUE TITLE
Interaction of plone.api (any version) with plone.app.multilingual -> CSRF issues 

### ISSUE THREAD

**Issue by zopyx** [plone/plone.app.multilingual#315]
See

https://github.com/plone/plone.restapi/issues/527

...not sure about the "guilty" module in this combination of plone.app.multilingual and plone.restapi.

**Comment by datakurre** [comment]
PAM is ”guilty”. Its ITranslationManager(context) adapter does the write

https://github.com/plone/plone.app.multilingual/commit/99c2eb591a271d9a678d137a898b778219b1d51f#diff-079d2a32162b70d6475311073a2f1669R45

I don’t know why that was necessary, or can that write be safely removed. I wonder if this only happens when PAM is enabled on a site with existing content.

REST API could workaround this by checking for existence translations in a safer manner:

https://github.com/plone/plone.app.multilingual/commit/a9371792b67a21b433f7529eed1f99159113fc3f

/cc @erral

**Comment by zopyx** [comment]
I also think that plone.app.multilingual is guilty here but I wonder why the default front-page (which is not created through plone.restapi) has the same problem---I solved this issue with my own IObjectCreated subscriber with add _plone.tg to new objects.
