### ISSUE TITLE
Error in babel_helper.js "TypeError: a.position(...) is null"

### ISSUE THREAD

**Issue by pbauer** [plone/plone.app.multilingual#58]
In complex content-types with many fields I get "TypeError: a.position(...) is null" in line 23 where a is []. 
The js works in simpler types but breaks in several types with more than a few fields.
This happens with current master.

**Comment by jensens** [comment]
I think I fixed a related problem while fixing other fieldset related problems discovered for a project and while alpine city sprint. I'am not sure if this helps for this bug too. Could you try latest pam 2 if this problem still resists?

**Comment by djowett** [comment]
I had this issue today on [1.x branch](https://github.com/plone/plone.app.multilingual/commit/b33d4e705efb3eda07677bab913eb27cebe88d3f).  I'm working with Plone 4.3, plone.app.contenttypes & a custom behaviour on my types.
The fix suggested above by @ablumer works for me `destination_fields = $('#form-target fieldset .field:not(".field .field")');`.   Is there any reason not to make that into a Pull Request?

**Comment by djowett** [comment]
Or perhaps it could be simpler:

    destination_fields = $('#form-target fieldset > .field');

**Comment by djowett** [comment]
Right, correction - in actual fact this issue (for me) was to do with an image field (NamedBlogImage) in my customer behavior (and therefore schema).  I didn't have reference fields as @ablumer had/has, and in actual fact his fix, *didn't* resolve things for me (though it did get me on the right track).  
My issue is only with vertical alignment of fields & was caused by the babel_helper.js running *before* the image height was correctly resolved.  So the html says the height of the thumbnail is 320px, but because there isn't the width to fit that in it gets scaled down to 65px - but not before babel_helper.js has picked up on the height, so there ends up being 255px of blank space.

I can resolve this in my case with a bit of CSS, but I don't know how it might be fixed in general cases - perhaps binding the start of babel_helper.js to a later event?

    #form-widgets-IBannerImage-banner_image > img {
      /* Fix the height of the banner image on the babel edit form, which helps
       * with vertical alignment of the fields on e.g. a hard refresh */
      height: 65px;
    }

Don't keep this open on my account, but I can't say to close it either

**Comment by pbauer** [comment]
Closed due to long inactivity. Probably not relevant for for Plone 5.2 or 6.
